export PATH=~/.local/bin:$PATH
export VISUAL=nvim
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export EDITOR=nvim
export TERMINAL=kitty
export SHELL=/usr/bin/zsh
export QT_QPA_PLATFORMTHEME=qt5ct
export _JAVA_AWT_WM_NONREPARENTING=1

# export XKB_DEFAULT_LAYOUT="hr"
export XKB_DEFAULT_OPTIONS="caps:none"
# export KEYMAP=~/.local/share/kbd/keymaps/croat.map # custom keymap

export WALLPAPER=$(cat ~/Wallpapers/current_wallpaper)

alias startx="startx ~/.xinitrc"

if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  # exec qtile start -b wayland
  exec startx &> /dev/null
fi
