# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install

PROMPT_EOL_MARK=''

unset LINES
unset COLUMNS

alias dotdrop='/home/nikola/Documents/dev/dotfiles/dotdrop.sh --cfg=/home/nikola/Documents/dev/dotfiles/config.yaml'
alias ani-cli="ani-cli -q 480"
# [ "$TERM" = "xterm-kitty" ] && alias ssh="kitty +kitten ssh"

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/doc/pkgfile/command-not-found.zsh

autoload -Uz compinit
compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' rehash true

 
function zle-line-init zle-keymap-select {
    case ${KEYMAP} in
        (vicmd)      mode="N" ;;
        (main|viins) mode="I" ;;
        (*)          mode="I" ;;
    esac
		branch=$(git symbolic-ref HEAD 2> /dev/null | awk 'BEGIN{FS="/"} {print $NF}')
		if [ "$branch" != "" ]; then
			branch="%F{15}(%F{202}$branch%F{15}) "
		fi
        PS1="  ${VIRTUAL_ENV:t}
 $branch%F{15}%~ %F{202}$mode %F{15}>>%f "
    zle reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select

setopt +o nomatch
source *env/bin/activate &> /dev/null
