local nest = require("nest")

nest.applyKeymaps({
	{
		mode = "v",
		{
			{ "<ScrollWheelUp>", "<nop>" },
			{ "<ScrollWheelDown>", "<nop>" },
			{ "<ScrollWheelLeft>", "<nop>" },
			{ "<ScrollWheelRight>", "<nop>" },
			{ "<LeftMouse>", "<nop>" },
			{ "<LeftDrag>", "<nop>" },
			{ "<RightMouse>", "<nop>" },
			{ "<RightDrag>", "<nop>" },
			{ "<MiddleMouse>", "<nop>" },
			{
				"<2-",
				{
					{ "-LeftMouse>", "<nop>" },
					{ "-LeftDrag>", "<nop>" },
					{ "-RightMouse>", "<nop>" },
					{ "-RightDrag>", "<nop>" },
					{ "-MiddleMouse>", "<nop>" },
				},
			},
			{
				"<3-",
				{
					{ "-LeftMouse>", "<nop>" },
					{ "-LeftDrag>", "<nop>" },
					{ "-RightMouse>", "<nop>" },
					{ "-RightDrag>", "<nop>" },
					{ "-MiddleMouse>", "<nop>" },
				},
			},
			{
				"<4-",
				{
					{ "-LeftMouse>", "<nop>" },
					{ "-LeftDrag>", "<nop>" },
					{ "-RightMouse>", "<nop>" },
					{ "-RightDrag>", "<nop>" },
					{ "-MiddleMouse>", "<nop>" },
				},
			},
			{
				"<A-",
				{
					{ "ScrollWheelUp>", "<nop>" },
					{ "ScrollWheelDown>", "<nop>" },
					{ "ScrollWheelLeft>", "<nop>" },
					{ "ScrollWheelRight>", "<nop>" },
					{ "LeftMouse>", "<nop>" },
					{ "LeftDrag>", "<nop>" },
					{ "RightMouse>", "<nop>" },
					{ "RightDrag>", "<nop>" },
					{ "MiddleMouse>", "<nop>" },
					{
						"2-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
					{
						"3-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
					{
						"4-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
				},
			},
			{
				"<C-",
				{
					{ "ScrollWheelUp>", "<nop>" },
					{ "ScrollWheelDown>", "<nop>" },
					{ "ScrollWheelLeft>", "<nop>" },
					{ "ScrollWheelRight>", "<nop>" },
					{ "LeftMouse>", "<nop>" },
					{ "LeftDrag>", "<nop>" },
					{ "RightMouse>", "<nop>" },
					{ "RightDrag>", "<nop>" },
					{ "MiddleMouse>", "<nop>" },
					{
						"2-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
					{
						"3-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
					{
						"4-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
				},
			},
			{
				"<S-",
				{
					{ "ScrollWheelUp>", "<nop>" },
					{ "ScrollWheelDown>", "<nop>" },
					{ "ScrollWheelLeft>", "<nop>" },
					{ "ScrollWheelRight>", "<nop>" },
					{ "LeftMouse>", "<nop>" },
					{ "LeftDrag>", "<nop>" },
					{ "RightMouse>", "<nop>" },
					{ "RightDrag>", "<nop>" },
					{ "MiddleMouse>", "<nop>" },
					{
						"2-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
					{
						"3-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
					{
						"4-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
				},
			},
		},
	},
	{
		mode = "i",
		{
			{ "<ScrollWheelUp>", "<nop>" },
			{ "<ScrollWheelDown>", "<nop>" },
			{ "<ScrollWheelLeft>", "<nop>" },
			{ "<ScrollWheelRight>", "<nop>" },
			{ "<LeftMouse>", "<nop>" },
			{ "<LeftDrag>", "<nop>" },
			{ "<RightMouse>", "<nop>" },
			{ "<RightDrag>", "<nop>" },
			{ "<MiddleMouse>", "<nop>" },
			{
				"<2-",
				{
					{ "-LeftMouse>", "<nop>" },
					{ "-LeftDrag>", "<nop>" },
					{ "-RightMouse>", "<nop>" },
					{ "-RightDrag>", "<nop>" },
					{ "-MiddleMouse>", "<nop>" },
				},
			},
			{
				"<3-",
				{
					{ "-LeftMouse>", "<nop>" },
					{ "-LeftDrag>", "<nop>" },
					{ "-RightMouse>", "<nop>" },
					{ "-RightDrag>", "<nop>" },
					{ "-MiddleMouse>", "<nop>" },
				},
			},
			{
				"<4-",
				{
					{ "-LeftMouse>", "<nop>" },
					{ "-LeftDrag>", "<nop>" },
					{ "-RightMouse>", "<nop>" },
					{ "-RightDrag>", "<nop>" },
					{ "-MiddleMouse>", "<nop>" },
				},
			},
			{
				"<A-",
				{
					{ "ScrollWheelUp>", "<nop>" },
					{ "ScrollWheelDown>", "<nop>" },
					{ "ScrollWheelLeft>", "<nop>" },
					{ "ScrollWheelRight>", "<nop>" },
					{ "LeftMouse>", "<nop>" },
					{ "LeftDrag>", "<nop>" },
					{ "RightMouse>", "<nop>" },
					{ "RightDrag>", "<nop>" },
					{ "MiddleMouse>", "<nop>" },
					{
						"2-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
					{
						"3-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
					{
						"4-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
				},
			},
			{
				"<C-",
				{
					{ "ScrollWheelUp>", "<nop>" },
					{ "ScrollWheelDown>", "<nop>" },
					{ "ScrollWheelLeft>", "<nop>" },
					{ "ScrollWheelRight>", "<nop>" },
					{ "LeftMouse>", "<nop>" },
					{ "LeftDrag>", "<nop>" },
					{ "RightMouse>", "<nop>" },
					{ "RightDrag>", "<nop>" },
					{ "MiddleMouse>", "<nop>" },
					{
						"2-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
					{
						"3-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
					{
						"4-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
				},
			},
			{
				"<S-",
				{
					{ "ScrollWheelUp>", "<nop>" },
					{ "ScrollWheelDown>", "<nop>" },
					{ "ScrollWheelLeft>", "<nop>" },
					{ "ScrollWheelRight>", "<nop>" },
					{ "LeftMouse>", "<nop>" },
					{ "LeftDrag>", "<nop>" },
					{ "RightMouse>", "<nop>" },
					{ "RightDrag>", "<nop>" },
					{ "MiddleMouse>", "<nop>" },
					{
						"2-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
					{
						"3-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
					{
						"4-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
				},
			},
		},
	},
	{
		mode = "n",
		{
			{ "<ScrollWheelUp>", "<nop>" },
			{ "<ScrollWheelDown>", "<nop>" },
			{ "<ScrollWheelLeft>", "<nop>" },
			{ "<ScrollWheelRight>", "<nop>" },
			{ "<LeftMouse>", "<nop>" },
			{ "<LeftDrag>", "<nop>" },
			{ "<RightMouse>", "<nop>" },
			{ "<RightDrag>", "<nop>" },
			{ "<MiddleMouse>", "<nop>" },
			{
				"<2-",
				{
					{ "-LeftMouse>", "<nop>" },
					{ "-LeftDrag>", "<nop>" },
					{ "-RightMouse>", "<nop>" },
					{ "-RightDrag>", "<nop>" },
					{ "-MiddleMouse>", "<nop>" },
				},
			},
			{
				"<3-",
				{
					{ "-LeftMouse>", "<nop>" },
					{ "-LeftDrag>", "<nop>" },
					{ "-RightMouse>", "<nop>" },
					{ "-RightDrag>", "<nop>" },
					{ "-MiddleMouse>", "<nop>" },
				},
			},
			{
				"<4-",
				{
					{ "-LeftMouse>", "<nop>" },
					{ "-LeftDrag>", "<nop>" },
					{ "-RightMouse>", "<nop>" },
					{ "-RightDrag>", "<nop>" },
					{ "-MiddleMouse>", "<nop>" },
				},
			},
			{
				"<A-",
				{
					{ "ScrollWheelUp>", "<nop>" },
					{ "ScrollWheelDown>", "<nop>" },
					{ "ScrollWheelLeft>", "<nop>" },
					{ "ScrollWheelRight>", "<nop>" },
					{ "LeftMouse>", "<nop>" },
					{ "LeftDrag>", "<nop>" },
					{ "RightMouse>", "<nop>" },
					{ "RightDrag>", "<nop>" },
					{ "MiddleMouse>", "<nop>" },
					{
						"2-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
					{
						"3-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
					{
						"4-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
				},
			},
			{
				"<C-",
				{
					{ "ScrollWheelUp>", "<nop>" },
					{ "ScrollWheelDown>", "<nop>" },
					{ "ScrollWheelLeft>", "<nop>" },
					{ "ScrollWheelRight>", "<nop>" },
					{ "LeftMouse>", "<nop>" },
					{ "LeftDrag>", "<nop>" },
					{ "RightMouse>", "<nop>" },
					{ "RightDrag>", "<nop>" },
					{ "MiddleMouse>", "<nop>" },
					{
						"2-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
					{
						"3-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
					{
						"4-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
				},
			},
			{
				"<S-",
				{
					{ "ScrollWheelUp>", "<nop>" },
					{ "ScrollWheelDown>", "<nop>" },
					{ "ScrollWheelLeft>", "<nop>" },
					{ "ScrollWheelRight>", "<nop>" },
					{ "LeftMouse>", "<nop>" },
					{ "LeftDrag>", "<nop>" },
					{ "RightMouse>", "<nop>" },
					{ "RightDrag>", "<nop>" },
					{ "MiddleMouse>", "<nop>" },
					{
						"2-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
					{
						"3-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
					{
						"4-",
						{
							{ "-LeftMouse>", "<nop>" },
							{ "-LeftDrag>", "<nop>" },
							{ "-RightMouse>", "<nop>" },
							{ "-RightDrag>", "<nop>" },
							{ "-MiddleMouse>", "<nop>" },
						},
					},
				},
			},
		},
	},
})
