#!/bin/sh

# lxsession &
lxpolkit &
numlockx &
picom -b &
xset s off &
nm-applet &
udiskie -s &
blueman-applet &
autorandr -c &
system-config-printer-applet &
calcurse --daemon &
notify-send "$(calcurse -a)" &
xsetroot -cursor_name left_ptr &
feh --bg-scale ${WALLPAPER}
# lemonbar_sh | lemonbar -o -2 -f "mmcedar" -f "iosevka" -g 1888x20+16+6 | sh &
lemonbar_rust &
stalonetray &
volume_monitor &
# firewall-applet &
# discord &
# protonvpn-applet &
