#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

~/.config/bspwm/bsp_autostart 2> /dev/null &

bspc monitor -d 一 二 三 四 五 六 七 八 九

bspc config border_width         2
bspc config window_gap           6

bspc config normal_border_color "#440000"
bspc config active_border_color "#440000"
bspc config focused_border_color "#ff0000"
bspc config presel_feedback_color "#880000"

bspc config split_ratio          0.5

bspc config click_to_focus none
# bspc config pointer_follows_focus true
# bspc config pointer_follows_monitor true
bspc config ignore_ewmh_focus true
bspc config honor_size_hits true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Screenkey manage=off

~/.config/bspwm/bsp_monocle_transparency_fix &
