config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_xmodmap:
    src: Xmodmap
    dst: ~/.Xmodmap
  f_rtorrent.rc:
    src: rtorrent.rc
    dst: ~/.rtorrent.rc
    chmod: '755'
  f_weather:
    src: local/bin/weather
    dst: ~/.local/bin/weather
    chmod: '755'
  f_toggle_picom:
    src: local/bin/toggle_picom
    dst: ~/.local/bin/toggle_picom
    chmod: '755'
  f_screenshot:
    src: local/bin/screenshot
    dst: ~/.local/bin/screenshot
    chmod: '755'
  f_screenshot_select:
    src: local/bin/screenshot_select
    dst: ~/.local/bin/screenshot_select
    chmod: '755'
  f_public_ip:
    src: local/bin/public_ip
    dst: ~/.local/bin/public_ip
    chmod: '755'
  d_autorandr:
    src: config/autorandr
    dst: ~/.config/autorandr
  d_cava:
    src: config/cava
    dst: ~/.config/cava
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  f_kitty.conf:
    src: config/kitty/kitty.conf
    dst: ~/.config/kitty/kitty.conf
  d_maestral:
    src: config/maestral
    dst: ~/.config/maestral
  d_neofetch:
    src: config/neofetch
    dst: ~/.config/neofetch
  d_picom:
    src: config/picom
    dst: ~/.config/picom
  f_autostart.sh:
    src: config/qtile/autostart.sh
    dst: ~/.config/qtile/autostart.sh
    chmod: '755'
  f_config.py:
    src: config/qtile/config.py
    dst: ~/.config/qtile/config.py
  d_qutebrowser:
    src: config/qutebrowser
    dst: ~/.config/qutebrowser
    chmod: '700'
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_zathura:
    src: config/zathura
    dst: ~/.config/zathura
  d_xorg.conf.d:
    src: etc/X11/xorg.conf.d
    dst: /etc/X11/xorg.conf.d
  f_lxpolkit.desktop:
    src: etc/xdg/autostart/lxpolkit.desktop
    dst: /etc/xdg/autostart/lxpolkit.desktop
  d_grub_theme_higurashi:
    src: boot/grub/themes/grub_theme_higurashi
    dst: /boot/grub/themes/grub_theme_higurashi
  d_mutt:
    src: config/mutt
    dst: ~/.config/mutt
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_zprofile:
    src: zprofile
    dst: ~/.zprofile
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
    chmod: '755'
  d_colors:
    src: config/nvim/colors
    dst: ~/.config/nvim/colors
  d_calcurse:
    src: config/calcurse
    dst: ~/.config/calcurse
    chmod: '700'
  f_tooltip-gtk2.qss:
    src: config/qt5ct/qss/tooltip-gtk2.qss
    dst: ~/.config/qt5ct/qss/tooltip-gtk2.qss
  f_mimeapps.list:
    src: config/mimeapps.list
    dst: ~/.config/mimeapps.list
  f_clear-torents:
    src: local/bin/clear-torents
    dst: ~/.local/bin/clear-torents
    chmod: '755'
  f_qpassword_manager.desktop:
    src: local/share/applications/qpassword_manager.desktop
    dst: ~/.local/share/applications/qpassword_manager.desktop
profiles:
  Arch:
    dotfiles:
    - f_xinitrc
    - f_xresources
    - f_xmodmap
    - f_rtorrent.rc
    - f_weather
    - f_toggle_picom
    - f_screenshot
    - f_screenshot_select
    - f_public_ip
    - d_autorandr
    - d_cava
    - d_dunst
    - f_kitty.conf
    - d_maestral
    - d_neofetch
    - d_picom
    - f_autostart.sh
    - f_config.py
    - d_qutebrowser
    - d_ranger
    - d_rofi
    - d_zathura
    - d_xorg.conf.d
    - f_lxpolkit.desktop
    - d_grub_theme_higurashi
    - d_mutt
    - f_zshrc
    - f_zprofile
    - f_init.vim
    - d_colors
    - d_calcurse
    - f_tooltip-gtk2.qss
    - f_mimeapps.list
    - f_clear-torents
    - f_qpassword_manager.desktop
