config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
    chmod: '755'
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_xmodmap:
    src: Xmodmap
    dst: ~/.Xmodmap
  f_rtorrent.rc:
    src: rtorrent.rc
    dst: ~/.rtorrent.rc
    chmod: '755'
  f_weather:
    src: local/bin/weather
    dst: ~/.local/bin/weather
    chmod: '755'
  f_toggle_picom:
    src: local/bin/toggle_picom
    dst: ~/.local/bin/toggle_picom
    chmod: '755'
  f_screenshot:
    src: local/bin/screenshot
    dst: ~/.local/bin/screenshot
    chmod: '755'
  f_screenshot_select:
    src: local/bin/screenshot_select
    dst: ~/.local/bin/screenshot_select
    chmod: '755'
  f_public_ip:
    src: local/bin/public_ip
    dst: ~/.local/bin/public_ip
    chmod: '755'
  f_kitty.conf:
    src: config/kitty/kitty.conf
    dst: ~/.config/kitty/kitty.conf
  d_picom:
    src: config/picom
    dst: ~/.config/picom
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_zathura:
    src: config/zathura
    dst: ~/.config/zathura
  d_xorg.conf.d:
    src: etc/X11/xorg.conf.d
    dst: /etc/X11/xorg.conf.d
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_zprofile:
    src: zprofile
    dst: ~/.zprofile
  d_calcurse:
    src: config/calcurse
    dst: ~/.config/calcurse
    chmod: '700'
  f_tooltip-gtk2.qss:
    src: config/qt5ct/qss/tooltip-gtk2.qss
    dst: ~/.config/qt5ct/qss/tooltip-gtk2.qss
  f_mimeapps.list:
    src: config/mimeapps.list
    dst: ~/.config/mimeapps.list
  f_clear-torents:
    src: local/bin/clear-torents
    dst: ~/.local/bin/clear-torents
    chmod: '755'
  f_qpassword_manager.desktop:
    src: local/share/applications/qpassword_manager.desktop
    dst: ~/.local/share/applications/qpassword_manager.desktop
  d_qtile:
    src: config/qtile
    dst: ~/.config/qtile
  d_oomox:
    src: config/oomox
    dst: ~/.config/oomox
  d_colors:
    src: config/nvim/colors
    dst: ~/.config/nvim/colors
  f_init.lua:
    src: config/nvim/init.lua
    dst: ~/.config/nvim/init.lua
  d_lua:
    src: config/nvim/lua
    dst: ~/.config/nvim/lua
  f_config.py:
    src: config/qutebrowser/config.py
    dst: ~/.config/qutebrowser/config.py
  f_quickmarks:
    src: config/qutebrowser/quickmarks
    dst: ~/.config/qutebrowser/quickmarks
    chmod: '755'
  f_ryuuguurena.png:
    src: Wallpapers/RyuuguuRena.png
    dst: ~/Wallpapers/RyuuguuRena.png
  f_current_wallpaper:
    src: Wallpapers/current_wallpaper
    dst: ~/Wallpapers/current_wallpaper
  d_qutebrowser_default_page:
    src: Documents/qutebrowser_default_page
    dst: ~/Documents/qutebrowser_default_page
  f_rofi-power-menu:
    src: local/bin/rofi-power-menu
    dst: ~/.local/bin/rofi-power-menu
    chmod: '755'
  f_set_wallpaper:
    src: local/bin/set_wallpaper
    dst: ~/.local/bin/set_wallpaper
    chmod: '755'
  f_gamemode.ini:
    src: config/gamemode.ini
    dst: ~/.config/gamemode.ini
  f_20211021_065952.jpg:
    src: Wallpapers/20211021_065952.jpg
    dst: ~/Wallpapers/20211021_065952.jpg
  d_bspwm:
    src: config/bspwm
    dst: ~/.config/bspwm
  f_sxhkdrc:
    src: config/sxhkd/sxhkdrc
    dst: ~/.config/sxhkd/sxhkdrc
  f_stalonetrayrc:
    src: stalonetrayrc
    dst: ~/.stalonetrayrc
  f_dunst_volume:
    src: local/bin/dunst_volume
    dst: ~/.local/bin/dunst_volume
    chmod: '755'
  f_lemonbar_rust:
    src: local/bin/lemonbar_rust
    dst: ~/.local/bin/lemonbar_rust
    chmod: '755'
  f_typepass:
    src: local/bin/typepass
    dst: ~/.local/bin/typepass
    chmod: '755'
  f_dunst_brightness:
    src: local/bin/dunst_brightness
    dst: ~/.local/bin/dunst_brightness
    chmod: '755'
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_autorandr:
    src: config/autorandr
    dst: ~/.config/autorandr
  f_volume_monitor:
    src: local/bin/volume_monitor
    dst: ~/.local/bin/volume_monitor
    chmod: '755'
profiles:
  ShiNoNeko47:
    dotfiles:
    - f_xinitrc
    - f_xresources
    - f_xmodmap
    - f_rtorrent.rc
    - f_weather
    - f_toggle_picom
    - f_screenshot
    - f_screenshot_select
    - f_public_ip
    - f_kitty.conf
    - d_picom
    - d_ranger
    - d_rofi
    - d_zathura
    - d_xorg.conf.d
    - f_zshrc
    - f_zprofile
    - d_calcurse
    - f_tooltip-gtk2.qss
    - f_mimeapps.list
    - f_clear-torents
    - f_qpassword_manager.desktop
    - d_qtile
    - d_oomox
    - d_colors
    - f_init.lua
    - d_lua
    - f_config.py
    - f_quickmarks
    - f_ryuuguurena.png
    - f_current_wallpaper
    - d_qutebrowser_default_page
    - f_rofi-power-menu
    - f_set_wallpaper
    - f_gamemode.ini
    - f_20211021_065952.jpg
    - d_bspwm
    - f_sxhkdrc
    - f_stalonetrayrc
    - f_dunst_volume
    - f_lemonbar_rust
    - f_typepass
    - f_dunst_brightness
    - d_dunst
    - d_autorandr
    - f_volume_monitor
