require("impatient")
require("user.options")
vim.cmd([[
  colorscheme Rena
]])
require("user.plugins")
require("user.luasnip")
require("user.lsp")
require("user.nvim-tree")
-- require("user.lsp.null-ls")
require("user.toggleterm")
-- require("user.indentline")
require("user.telescope")
require("user.lualine")
require("user.project")
-- require("user.treesitter")
require("user.markdown-preview")
require("user.bufferline")
require("Comment").setup()
require("user.dap")
require("user.keymaps")
require("numb").setup()
-- require("twilight").setup()
require("user.notify")
require("user.rust-tools")
require("user.crates")
require("user.cmp")
